require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
  - "lib/generators/blacklight/templates/**/*"
  - "spec/**/*"
  - "blacklight.gemspec"

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "lib/railties/blacklight.rake"
    - "tasks/blacklight.rake"

Metrics/LineLength:
  Max: 200

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/IndentationConsistency:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Style/MethodMissing:
  Exclude:
  - 'lib/blacklight/utils.rb'

# engine_cart block includes conditional, not duplication
Bundler/DuplicatedGem:
  Exclude:
  - 'Gemfile'

# engine_cart block is following default Rails order
Bundler/OrderedGems:
  Exclude:
  - 'Gemfile'
