require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - "blacklight.gemspec"
    - "db/**/*"
    - "lib/generators/blacklight/templates/**/*"
    - "spec/**/*"

Rails:
  Enabled: true

# TODO: remove when
# https://github.com/bbatsov/rubocop/commit/246bef5e1cccd04045a71eee2476cde6c0782e92
# is part fo a stable release
Rails/Blank:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "lib/railties/blacklight.rake"
    - "tasks/blacklight.rake"

Metrics/LineLength:
  Max: 200

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/IndentationConsistency:
  EnforcedStyle: normal

Rails/OutputSafety:
  Enabled: false

Style/MethodMissing:
  Exclude:
  - 'lib/blacklight/utils.rb'

# engine_cart block includes conditional, not duplication
Bundler/DuplicatedGem:
  Exclude:
  - 'Gemfile'

# engine_cart block is following default Rails order
Bundler/OrderedGems:
  Exclude:
  - 'Gemfile'
