require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
  - "lib/generators/blacklight/templates/**/*"
  - "blacklight.gemspec"

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "app/views/catalog/index.json.jbuilder"
    - "lib/railties/blacklight.rake"
    - "tasks/blacklight.rake"
    - "spec/**/*"

Metrics/ClassLength:
  Exclude:
    - "lib/blacklight/configuration.rb"

Metrics/LineLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: normal

Rails/OutputSafety:
  Enabled: false

Style/MissingRespondToMissing:
  Exclude:
  - 'lib/blacklight/nested_open_struct_with_hash_access.rb'

# engine_cart block includes conditional, not duplication
Bundler/DuplicatedGem:
  Exclude:
  - 'Gemfile'

# engine_cart block is following default Rails order
Bundler/OrderedGems:
  Exclude:
  - 'Gemfile'

Naming/HeredocDelimiterNaming:
  Enabled: false
