services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      args:
        - ALPINE_RUBY_VERSION
    # mounting . is causing seg-fault on macosx
    #volumes:
    #- .:/app
    depends_on:
      - solr
    ports:
      - "3000:3000"
    environment:
      - SOLR_URL # Set via environment variable or use default defined in .env file
      - RAILS_VERSION # Set via environment variable or use default defined in .env file
      - VIEW_COMPONENT_VERSION # Set via environment variable or use default defined in .env file
      - SOLR_ENV=docker-compose
      - ENGINE_CART_RAILS_OPTIONS=--skip-git --skip-listen --skip-spring --skip-keeps --skip-action-cable --skip-coffee --skip-test --skip-solr

  solr:
    environment:
      - SOLR_PORT # Set via environment variable or use default defined in .env file
      - SOLR_VERSION # Set via environment variable or use default defined in .env file
      - SOLR_MODULES=analysis-extras
    image: "solr:${SOLR_VERSION}"
    volumes:
      - $PWD/lib/generators/blacklight/templates/solr/conf:/opt/solr/conf
    ports:
      - "${SOLR_PORT}:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight-core
      - /opt/solr/conf
      - "-Xms256m"
      - "-Xmx512m"

  elasticsearch:
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    image: elasticsearch:8.17.3
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
volumes:
  es_data:
