on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: ''
        description: The branch or reference to run the workflow against
jobs:
  set_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Echo ./.github/matrix.json
        id: matrix
        run: |
          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          cat ./.github/matrix.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  test:
    needs: set_matrix
    runs-on: ubuntu-latest
    name: ruby ${{ matrix.ruby }} | rails ${{ matrix.rails_version }} ${{ matrix.additional_name }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.set_matrix.outputs.matrix)}}
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
      SOLR_VERSION: ${{ matrix.solr_version || 'latest' }}
      VIEW_COMPONENT_VERSION: ${{ matrix.view_component_version }}
      BOOTSTRAP_VERSION: ${{ matrix.bootstrap_version }}
      BLACKLIGHT_API_TEST: ${{ matrix.api }}
      ENGINE_CART_RAILS_OPTIONS: "--skip-git --skip-listen --skip-spring --skip-keeps --skip-kamal --skip-solid --skip-coffee --skip-test ${{ matrix.additional_engine_cart_rails_options }}"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: "latest"
          ruby-version: ${{ matrix.ruby }}
      - name: Change permissions
        run: "chmod -f -R o-w /opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems | :"
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake ci
