on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: ''
        description: The branch or reference to run the workflow against
      ruby:
        required: true
        type: string
        description: The Ruby or Rubies used in the matrix. Must be in format '["ruby.version"]'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.project }}
    - run: echo ${{ matrix.config }}
  # test:
  #   runs-on: ubuntu-latest
  #   name: ruby ${{ matrix.ruby }} | rails ${{ matrix.rails_version }} ${{ matrix.additional_name }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       ruby: ${{ fromJSON(inputs.ruby) }}
  #       rails_version: ["7.1.5.1", "7.2.2.1"]
  #       bootstrap_version: [null]
  #       view_component_version: ["~> 3.12"]
  #       api: [null]
  #       additional_engine_cart_rails_options: [""]
  #       additional_name: [""]
  #       include:
  #         - ruby: "3.3"
  #           rails_version: "8.0.1"
  #           additional_engine_cart_rails_options: --css=bootstrap
  #         - ruby: "3.3"
  #           rails_version: "8.0.1"
  #           additional_engine_cart_rails_options: --css=bootstrap --js=esbuild
  #           additional_name: "| esbuild"
  #         - ruby: "3.2"
  #           rails_version: "7.1.5.1"
  #           solr_version: "8.11.2"
  #           additional_name: "| Solr 8.11.2"
  #         - ruby: "3.3"
  #           rails_version: "7.1.5.1"
  #           additional_name: "| Propshaft"
  #           additional_engine_cart_rails_options: -a propshaft --css=bootstrap
  #         - ruby: "3.3"
  #           rails_version: "7.1.5.1"
  #           api: "true"
  #           additional_engine_cart_rails_options: --api --skip-yarn
  #           additional_name: "| API"
  #         - ruby: "3.3"
  #           rails_version: "7.2.2.1"
  #           additional_engine_cart_rails_options: -a propshaft --css=bootstrap --js=esbuild
  #           additional_name: "| Propshaft, esbuild"
  #   env:
  #     RAILS_VERSION: ${{ matrix.rails_version }}
  #     SOLR_VERSION: ${{ matrix.solr_version || 'latest' }}
  #     VIEW_COMPONENT_VERSION: ${{ matrix.view_component_version }}
  #     BOOTSTRAP_VERSION: ${{ matrix.bootstrap_version }}
  #     BLACKLIGHT_API_TEST: ${{ matrix.api }}
  #     ENGINE_CART_RAILS_OPTIONS: "--skip-git --skip-listen --skip-spring --skip-keeps --skip-kamal --skip-solid --skip-coffee --skip-test ${{ matrix.additional_engine_cart_rails_options }}"
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: ${{ inputs.ref }}
  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         bundler: "latest"
  #         ruby-version: ${{ matrix.ruby }}
  #     - name: Change permissions
  #       run: "chmod -f -R o-w /opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems | :"
  #     - name: Install dependencies
  #       run: bundle install
  #     - name: Run tests
  #       run: bundle exec rake ci
